_target_: src.models.speclab_module.SpecLabLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.aspp.SRDetectModel
  drop_rate: 0.4
  bn_momentum: 0.1
  base_num_filters: 64

