# @package _global_

defaults:
  - _self_
  - datamodule: speclab.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: speclab.yaml
  - logger: wandb.yaml
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

log_image: false

# passing checkpoint path is necessary for evaluation
ckpt_path: /content/SpecLab/logs/model_checkpoints/epoch_000.ckpt
