# @package _global_

defaults:
  - _self_
  - datamodule: pred.yaml # use speclab.yaml to run metrics
  - model: speclab.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "pred"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /content/SpecLab/logs/model_checkpoints/epoch_000.ckpt
