_target_: src.datamodules.speclab_datamodule.SpecLabDataModule
img_dir: /content/GLENDA_img
mask_dir: /content/GLENDA_mask
batch_size: 4
train_val_test_split: [7_331, 2_443, 2_444]
num_workers: 4
pin_memory: True
